### ISSUE TITLE
Can not run basic example

### ISSUE THREAD

**Issue by eelcovv** [maresb/ansible-micromamba-role#3]
I tried to run the exmple you give. I have the following playbook:

```
- hosts: 
  -  ubun22orweb
  become: yes
  roles:
    - mambaorg.micromamba
  vars:
    arch: linux-aarch64
    dest: /tmp/micromamba
    root_prefix: /opt/conda
    root_prefix_condarc:
      channels:
        - conda-forge
    packages:
      - mamba
      - python=3.9
```

I have a seperate host file with the conent:

```
all: 
  vars:
    ansible_connection: lxd
    ansible_user: root
    ansible_become: no
  children:
    local:
      vars:
        ansible_lxd_remote: local
      hosts:
        ubun22ordsk: 
        ubun22orweb: 

```

Running the following command fails:

`ansible-playbook -i host.yml  mamba.yml 
`
The error is : 
```

PLAY [ubun22orweb] ********************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
ok: [ubun22orweb]

TASK [mambaorg.micromamba : Check if micromamba already exists in /tmp/micromamba] ****************************************************
ok: [ubun22orweb]

TASK [mambaorg.micromamba : Make temporary directory for micromamba] ******************************************************************
changed: [ubun22orweb]

TASK [mambaorg.micromamba : Install micromamba] ***************************************************************************************
fatal: [ubun22orweb]: FAILED! => {"changed": false, "msg": "Failed to find handler for \"/root/.ansible/tmp/ansible-tmp-1673189910.9980383-723056-39328482899404/latestbv6vtfan\". Make sure the required command to extract the file is installed. Command \"/usr/bin/unzip\" could not handle archive. Command \"/usr/bin/tar\" could not handle archive."}

PLAY RECAP ****************************************************************************************************************************
ubun22orweb                : ok=3    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   

```

Any idea what could be wrong?
