### ISSUE TITLE
Use new repository `mamba-org/micromamba-releases` for download

### ISSUE THREAD

**Issue by pavelzw** [maresb/ansible-micromamba-role#7]
There is a new source for micromamba releases at [mamba-org/micromamba-releases](https://github.com/mamba-org/micromamba-releases/releases). There you can download the binaries directly without needing to extract them. This would make this role usable on systems where bzip2 is not installed.

In https://micromamba.pfx.dev/install.sh the release URL is generated as follows:
```bash
if [[ "${VERSION:-}" == "" ]]; then
  RELEASE_URL=https://github.com/mamba-org/micromamba-releases/releases/latest/download/micromamba-$PLATFORM-$ARCH
else
  RELEASE_URL=https://github.com/mamba-org/micromamba-releases/releases/download/micromamba-$VERSION/micromamba-$PLATFORM-$ARCH
fi
```

**Comment by maresb** [comment]
Hey @pavelzw, sorry this slipped my radar. Would there still be value in fixing this?

**Comment by pavelzw** [comment]
For me personally not really; I don't use this role because I only need to install micromamba and nothing else in Ansible.
For this, it's easier to use the following:

```yml
    - name: Install micromamba
      ansible.builtin.get_url:
        url: https://github.com/mamba-org/micromamba-releases/releases/download/{{ micromamba.version }}/micromamba-linux-64
        dest: /usr/local/bin/micromamba
        checksum: sha256:{{ micromamba.sha256 }}
        mode: '0755'
      register: result
      until: result is succeeded
      retries: 3
      delay: 10
      environment: "{{ proxy_env }}"
```
